#!/bin/python3

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:
1,2,3,5,8,13,...
By considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.

Input Format
First line contains  that denotes the number of test cases. This is followed by  lines, each containing an integer, .
"""
import sys

t = int(input().strip())
fibonacciNums = [1, 2]
count = 0
for a0 in range(t):
    n = int(input().strip())
    while fibonacciNums[-1] < n:
        fibonacciNums.append(fibonacciNums[count] + fibonacciNums[count + 1])
        count += 1
    
    result = 0
    for num in fibonacciNums:
        if num % 2 == 0 and num < n:
            result += num
        else:
            continue
    print(result)
